In [3]:
list1 = list(range(1,41))

print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


In [8]:
import numpy as np
arr = np.array(list1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [12]:
tpl = tuple(range(1,41))

print(tpl)

arr = np.array(tpl)

print(arr)
print(arr.shape)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
(40,)


In [13]:
## 2D Array

In [1]:
list2d = [list(range(1,5)),list(range(6,10))]

print(list2d)

[[1, 2, 3, 4], [6, 7, 8, 9]]


In [27]:
print(type(list2d))

<class 'list'>


In [3]:

import numpy as np
arr2d = np.array(list2d)
print(arr2d)

[[1 2 3 4]
 [6 7 8 9]]


In [7]:
print(arr2d[[0,1,0],[1,3,2]])

[2 9 3]


In [30]:
arr = np.arange(10) ## Dynamic array creation

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
arr = np.arange(1,11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
arr = np.arange(0,51,5) ## start value, stop vlaue (exclusive), increment value

print(arr)

[ 0  5 10 15 20 25 30 35 40 45 50]


In [43]:
arr = np.arange(1,51,4.5)

print(arr)

[ 1.   5.5 10.  14.5 19.  23.5 28.  32.5 37.  41.5 46.  50.5]


In [39]:
arr = np.linspace(1,50,6) ## start value, stop vlaue (inclusive), no. of elements/data poitns

print(arr)

[ 1.  10.8 20.6 30.4 40.2 50. ]


In [42]:
arr = np.ones(6)
print(arr)

[1. 1. 1. 1. 1. 1.]


In [45]:
arr = np.ones(6,dtype='int')
print(arr)

[1 1 1 1 1 1]


In [46]:
arr = np.zeros(6,dtype='int')
print(arr)

[0 0 0 0 0 0]


In [49]:
arr = np.zeros((6,7),dtype='int')
print(arr)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [50]:
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
arr = np.full((2,3),4)

print(arr)

[[4 4 4]
 [4 4 4]]


In [58]:
arr = np.diag([3,7,2,6])

print(arr)

[[3 0 0 0]
 [0 7 0 0]
 [0 0 2 0]
 [0 0 0 6]]


In [62]:
arr = np.eye(5, dtype='int')

print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [63]:
arr =np.random.random(5)

print(arr)

[0.43389818 0.07156506 0.28899487 0.74281369 0.32473622]


In [64]:
arr =np.random.random((2,5))

print(arr)

[[0.60937809 0.13453108 0.29051433 0.47721492 0.78280654]
 [0.8996066  0.95689671 0.04816369 0.87868084 0.67768642]]


In [81]:
arr =np.random.random((2,5))

print(arr)

[[0.13 0.35 0.92 0.75 0.09]
 [0.54 0.71 0.56 0.47 0.96]]


In [68]:
arr = np.random.randint(7)

print(arr)

2


In [83]:
arr = np.random.randint(1,100,size=(14,8))

print(arr)

[[34 67 89 88 28  9 56 74]
 [22 51  7 99 25  1 68 57]
 [15 22 46 90  8 86 75 13]
 [67 70 81 64 23 75 32  5]
 [57 95  1 38 57 94 29 12]
 [28 91 24 60 51  4 37  6]
 [61 91 65 60  2 39 86 91]
 [27 37 47  4 58 22  9 51]
 [16 51 89  1 52  6 99 19]
 [39 68 65 88 75 28 59 28]
 [80 66 33 95  3 85 83 45]
 [14 14 34  6 73  4 62  6]
 [72  8 38 59 97 44 50 92]
 [88 60 71 84 56 62 87 49]]


In [6]:
import numpy as np

arr = np.ones((4,2))

print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
%%time

import numpy as np

arr = np.arange(100000)

arr = arr*arr
print(arr)

[         0          1          4 ... 1409465417 1409665412 1409865409]
CPU times: total: 0 ns
Wall time: 537 µs


In [11]:
arr = np.array([1,3,4,5,7,8.0,-3])

print(arr)

print(arr.dtype)# Indexing and Broadcasting




[ 1.  3.  4.  5.  7.  8. -3.]
float64


# Indexing and Broadcasting

In [12]:
arr = np.arange(10)

print(arr)

print(arr[3])

arr = 3*arr
print(arr)

print(arr[3])


[0 1 2 3 4 5 6 7 8 9]
3
[ 0  3  6  9 12 15 18 21 24 27]
9


In [21]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)

print(arr[1][2])

print(arr[1,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
7


In [22]:
arr[1,2] = 8.0

print(arr)

print(arr.dtype)

[[ 1  2  3  4]
 [ 5  6  8  8]
 [ 9 10 11 12]]
int32


In [23]:
print(arr[::2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [24]:
print(arr[0:3])

[[ 1  2  3  4]
 [ 5  6  8  8]
 [ 9 10 11 12]]


In [25]:
print(arr[0:-1])

[[1 2 3 4]
 [5 6 8 8]]


In [26]:
print(arr[:2,1:3])

[[2 3]
 [6 8]]


In [27]:
print(arr[1:2,:])

[[5 6 8 8]]


In [32]:
print(arr[[0,1,2],[0,1,0]])

[1 6 9]


## Numpy Maths

In [53]:
## element Wise operations

x = np.array([[1,2],[5,6]])
y = np.array([[3,4],[7,8]])

print("addition of 2 arrays: ")
print(np.add(x,y),end="\n"*3)
print("Substraction of 2 arrays: ")
print(np.subtract(x,y),end="\n"*3)
print("Multiplication of 2 arrays: ")
print(np.multiply(x,y),end="\n"*3)
print("Division of 2 arrays: ")
print(np.divide(x,y))

addition of 2 arrays: 
[[ 4  6]
 [12 14]]


Substraction of 2 arrays: 
[[-2 -2]
 [-2 -2]]


Multiplication of 2 arrays: 
[[ 3  8]
 [35 48]]


Division of 2 arrays: 
[[0.33333333 0.5       ]
 [0.71428571 0.75      ]]


In [54]:
np.matmul(x,y)

array([[17, 20],
       [57, 68]])

In [55]:
np.dot(x,y)

array([[17, 20],
       [57, 68]])

In [56]:
np.sum(x)

14

In [59]:
x

array([[1, 2],
       [5, 6]])

In [57]:
np.sum(x,axis=0)

array([6, 8])

In [58]:
np.sum(x,axis=1)

array([ 3, 11])

In [145]:
a = np.array([[1,2],[3,4]])

b = np.array([[5,6],[7,8]])

c = np.array([9,10])

d= np.array([3])

e = np.array([3,4,5,6])

print(np.add(a,b))

print(np.add(b,c))

print(np.add(a,d))

print(np.add(a,e))

[[ 6  8]
 [10 12]]
[[14 16]
 [16 18]]
[[4 5]
 [6 7]]


ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [60]:
np.max(x)

6

In [61]:
np.min(x)

1

In [62]:
print(x)

print("*"*90)

print(x.T)

[[1 2]
 [5 6]]
******************************************************************************************
[[1 5]
 [2 6]]


In [68]:
a = np.array([[1,2,3],[4,5,6],[8,7,5]])

b = np.array([[2,3,8],[6,7,9],[7,3,9]])

print(np.dot(a,b))
              
              

[[ 35  26  53]
 [ 80  65 131]
 [ 93  88 172]]


In [69]:
print(np.min(a,axis=0))

[1 2 3]


In [71]:
print(np.max(a,axis=0))

[8 7 6]


In [72]:
a.T

array([[1, 4, 8],
       [2, 5, 7],
       [3, 6, 5]])

In [73]:
a = np.array([[1,2,3],[4,5,6]])

print(a)
print("*"*60)
print(a.T)

[[1 2 3]
 [4 5 6]]
************************************************************
[[1 4]
 [2 5]
 [3 6]]


In [85]:
arr = np.arange(1,50,5)

print(arr)


print(len(arr))



[ 1  6 11 16 21 26 31 36 41 46]
10


In [86]:
print(arr.reshape(1,10))

[[ 1  6 11 16 21 26 31 36 41 46]]


In [87]:
print(arr.reshape(2,5))

[[ 1  6 11 16 21]
 [26 31 36 41 46]]


In [88]:
print(arr.reshape(5,2))

[[ 1  6]
 [11 16]
 [21 26]
 [31 36]
 [41 46]]


In [89]:
print(arr.reshape(10,1))

[[ 1]
 [ 6]
 [11]
 [16]
 [21]
 [26]
 [31]
 [36]
 [41]
 [46]]


In [90]:
print(arr.reshape(3,3))

ValueError: cannot reshape array of size 10 into shape (3,3)

In [94]:
a = arr.reshape(2,1,5)

print(a)
print(a.shape)
print(a.size)

print(a.ndim)

[[[ 1  6 11 16 21]]

 [[26 31 36 41 46]]]
(2, 1, 5)
10
3


In [95]:
np.random.random()

0.8996365817191051

In [96]:
np.random.random(10)

array([0.36532779, 0.95017775, 0.41632038, 0.34564017, 0.33684178,
       0.27133115, 0.98841022, 0.62468464, 0.39254657, 0.07909722])

In [108]:
np.random.random(10,size=(2,5))

TypeError: random() got multiple values for keyword argument 'size'

In [103]:
np.random.randint(10)

array([[7, 3, 3, 4],
       [6, 4, 5, 5],
       [5, 1, 5, 9],
       [0, 1, 0, 6],
       [2, 6, 3, 9]])

In [115]:
arr1=np.random.randint(8,size=(4,6))

print(arr1)

[[6 1 2 7 3 6]
 [6 2 6 2 7 7]
 [4 0 0 6 6 3]
 [0 5 4 3 7 6]]


In [109]:
height = np.array([160,150,78,65])

weight = np.array([95,68,25,22])

np.corrcoef(height,weight)

array([[1.        , 0.97026036],
       [0.97026036, 1.        ]])

In [113]:
np.correlate(height,weight,mode='valid')

array([28780])

In [114]:
ls = np.linspace(1,10,10)

print(ls)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [116]:
 print(arr1)

[[6 1 2 7 3 6]
 [6 2 6 2 7 7]
 [4 0 0 6 6 3]
 [0 5 4 3 7 6]]


In [117]:
np.sort(arr1)

array([[1, 2, 3, 6, 6, 7],
       [2, 2, 6, 6, 7, 7],
       [0, 0, 3, 4, 6, 6],
       [0, 3, 4, 5, 6, 7]])

In [119]:
np.sort(arr1,axis=0)

array([[0, 0, 0, 2, 3, 3],
       [4, 1, 2, 3, 6, 6],
       [6, 2, 4, 6, 7, 6],
       [6, 5, 6, 7, 7, 7]])

In [120]:
arr1

array([[6, 1, 2, 7, 3, 6],
       [6, 2, 6, 2, 7, 7],
       [4, 0, 0, 6, 6, 3],
       [0, 5, 4, 3, 7, 6]])

In [121]:
np.sort_complex(arr1)

array([[1.+0.j, 2.+0.j, 3.+0.j, 6.+0.j, 6.+0.j, 7.+0.j],
       [2.+0.j, 2.+0.j, 6.+0.j, 6.+0.j, 7.+0.j, 7.+0.j],
       [0.+0.j, 0.+0.j, 3.+0.j, 4.+0.j, 6.+0.j, 6.+0.j],
       [0.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j]])

In [136]:
a1 = np.random.randint(1,50,size=(5,4))
print(a1)

[[19 36  4 31]
 [35 39 36 22]
 [21 22 29 30]
 [12 49 49 33]
 [22 29 25 13]]


In [139]:
np.where(a1%2==0,'even','Odd')

array([['Odd', 'even', 'even', 'Odd'],
       ['Odd', 'Odd', 'even', 'even'],
       ['Odd', 'even', 'Odd', 'even'],
       ['even', 'Odd', 'Odd', 'Odd'],
       ['even', 'Odd', 'Odd', 'Odd']], dtype='<U4')

array([['odd', '36', '4', 'odd'],
       ['odd', 'odd', '36', '22'],
       ['odd', '22', 'odd', '30'],
       ['12', 'odd', 'odd', 'odd'],
       ['22', 'odd', 'odd', 'odd']], dtype='<U11')